### ISSUE TITLE
google drive access denied

### ISSUE THREAD

**Issue by yundaehyuck** [hasibzunair/residual-acgpn-demo#1]
I want to use model. So I use this colab demo code, I see this issue in "second preprocessing cell"

# code

`import time

start_time = time.time()

remove_bg = False

img_name = 'person.png'
img_path = os.path.join('inputs/img', sorted(os.listdir('inputs/img'))[0])
img = Image.open(img_path)
if remove_bg:
  img = remove(img, alpha_matting=True, alpha_matting_erode_size=15)
  print("Removing background from person image..")
img = ImageOps.fit(img, (192, 256), Image.BICUBIC).convert("RGB")

**_img_mask = remove(img, alpha_matting=True, alpha_matting_erode_size=15, only_mask=True)_**
img_path = os.path.join('Data_preprocessing/test_img', img_name)
img.save(img_path)
resize_time = time.time()
print('Resized image in {}s'.format(resize_time-start_time))

!python3 Self-Correction-Human-Parsing-for-ACGPN/simple_extractor.py --dataset 'lip' --model-restore 'lip_final.pth' --input-dir 'Data_preprocessing/test_img' --output-dir 'Data_preprocessing/test_label'
parse_time = time.time()
print('Parsing generated in {}s'.format(parse_time-resize_time))

pose_path = os.path.join('Data_preprocessing/test_pose', img_name.replace('.png', '_keypoints.json'))
generate_pose_keypoints(img_path, pose_path)
pose_time = time.time()
print('Pose map generated in {}s'.format(pose_time-parse_time))`

# error

`Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1tCU5MM1LhRgGou5OpmpjBQbSrYIUoYab 

---------------------------------------------------------------------------
NoSuchFile                                Traceback (most recent call last)
[<ipython-input-13-7f19062a2848>](https://localhost:8080/#) in <module>
     15 img = ImageOps.fit(img, (192, 256), Image.BICUBIC).convert("RGB")
     16 # Get binary from person image
---> 17 img_mask = remove(img, alpha_matting=True, alpha_matting_erode_size=15, only_mask=True)
     18 img_path = os.path.join('Data_preprocessing/test_img', img_name)
     19 img.save(img_path)

3 frames
[/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py](https://localhost:8080/#) in _create_inference_session(self, providers, provider_options, disabled_optimizers)
    366         session_options = self._sess_options if self._sess_options else C.get_default_session_options()
    367         if self._model_path:
--> 368             sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
    369         else:
    370             sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)

NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from /root/.u2net/u2net.onnx failed:Load model /root/.u2net/u2net.onnx failed. File doesn't exist`

**Comment by hasibzunair** [comment]
@yundaehyuck, looks like it is a problem with the `rembg` package, were you able to solve it?

**Comment by yundaehyuck** [comment]
> @yundaehyuck, looks like it is a problem with the `rembg` package, were you able to solve it?

Thank you for your reply. I think that this code solve my problem.

!pip install -U --no-cache-dir gdown --pre
